### PR TITLE
PLANNER-2389 Remove version overrides

### PR DESCRIPTION
**Pull request by rsynek**
### JIRA
https://issues.redhat.com/browse/PLANNER-2389

### Referenced pull requests
https://github.com/kiegroup/optaplanner/pull/1254
https://github.com/kiegroup/optaplanner-quickstarts/pull/93
https://github.com/kiegroup/optaweb-employee-rostering/pull/602
https://github.com/kiegroup/optaweb-vehicle-routing/pull/471

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by rsynek** [comment]
Unfortunately, the only CI capable of incorporating changes to the `optaplanner-build-parent` is the Build Chain, which fails for some other reason.

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
jenkins retest this

**Comment by rsynek** [comment]
@yurloc is the `SolverIntegrationTest` stable? I noticed it sometimes fails locally too, even without the Quarkus version upgrade.

**Review by yurloc — APPROVED** [review]

**Comment by yurloc** [comment]
@rsynek Yes it seems unstable. I noticed the failure on Travis and I didn't have time to investigate it. Seeing it fail on GHA confirms the flakiness.

**Comment by rsynek** [comment]
Thanks for the confirmation; in that case, I am merging this PR.

**Pull request merged**
