### PR TITLE
BXMSPROD-963 pull_request.yml updated

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-963

[strategy.fail-fast](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) to **false** since java 11 is working
depends on:
- https://github.com/kiegroup/lienzo-core/pull/124
- https://github.com/kiegroup/lienzo-tests/pull/105
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1447
- https://github.com/kiegroup/kie-soup/pull/154
- https://github.com/kiegroup/appformer/pull/1037
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/459
- https://github.com/kiegroup/drools/pull/3063
- https://github.com/kiegroup/optaplanner/pull/901
- https://github.com/kiegroup/jbpm/pull/1739
- https://github.com/kiegroup/kie-jpmml-integration/pull/39
- https://github.com/kiegroup/droolsjbpm-integration/pull/2210
- https://github.com/kiegroup/openshift-drools-hacep/pull/97
- https://github.com/kiegroup/droolsjbpm-tools/pull/116
- https://github.com/kiegroup/kie-uberfire-extensions/pull/103
- https://github.com/kiegroup/kie-wb-playground/pull/94
- https://github.com/kiegroup/kie-wb-common/pull/3401
- https://github.com/kiegroup/drools-wb/pull/1414
- https://github.com/kiegroup/optaplanner-wb/pull/378
- https://github.com/kiegroup/jbpm-designer/pull/888
- https://github.com/kiegroup/jbpm-work-items/pull/142
- https://github.com/kiegroup/jbpm-wb/pull/1457
- https://github.com/kiegroup/kie-docs/pull/2787
- https://github.com/kiegroup/optaweb-employee-rostering/pull/492
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/353
- https://github.com/kiegroup/kie-wb-distributions/pull/1053

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by Ginxo** [comment]
`docker: failed to register layer: Error processing tar file(exit status 1): write /root/.cache/Cypress/3.6.0/Cypress/resources/app/packages/server/node_modules/ignore/ignore.js: no space left on device.`
I'm worried about this.
should be disable this build? Should we avoid cypress execution here?

**Comment by yurloc** [comment]
@Ginxo I think we should fix the environment or workflow configuration.

1. Cypress 3.6.0 [image](https://hub.docker.com/layers/cypress/included/3.6.0/images/sha256-db19b6b4bfc1a23ed0389a33b5e20fac0bd679f7959436fb5cbefe15434f1424?context=explore) is 700 MB.
2. Each [GitHub-hosted](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners) virtual machine has 14 GB disk space.

So it seems Cypress is no the problem.

What if we're consuming too much space by building all of the KIE projects? It's possible but I guess other builds would fail on this as well.

What if the VM has multiple partitions and `/root` is on a partition that doesn't have enough free space?

**Comment by Ginxo** [comment]
@yurloc @mareknovotny  this is the disk status before building appformer
```
[command]/bin/df -H
Filesystem      Size  Used Avail Use% Mounted on
udev            3.7G     0  3.7G   0% /dev
tmpfs           727M  979k  726M   1% /run
/dev/sdb1        90G   86G  3.6G  97% /
tmpfs           3.7G  8.2k  3.7G   1% /dev/shm
tmpfs           5.3M     0  5.3M   0% /run/lock
tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/loop1       42M   42M     0 100% /snap/hub/43
/dev/loop0      102M  102M     0 100% /snap/core/9804
/dev/sdb15      110M  3.8M  106M   4% /boot/efi
/dev/sda1        15G  4.4G  9.7G  32% /mnt
```
so, Docker is using /root folder (/dev/sdb1 mounting point) which has 3.6G, I'm going to change flow to remove every project which is already built.

**Comment by Ginxo** [comment]
`free disk space` step added but blocked by a compilation error not related with this change

**Pull request merged**
