### PR TITLE
BXMSPROD-1002 maven connection timeout

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1002

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by yurloc** [comment]
Java 11 check failed in `uberfire-commons`:
```
  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project uberfire-commons: Compilation failure: Compilation failure: 
  [ERROR] /home/runner/work/optaweb-vehicle-routing/optaweb-vehicle-routing/appformer/uberfire-commons/src/main/java/org/uberfire/commons/services/cdi/StartupType.java:[19,24] cannot find symbol
  [ERROR]   symbol:   class PostConstruct
  [ERROR]   location: package javax.annotation
  [ERROR] /home/runner/work/optaweb-vehicle-routing/optaweb-vehicle-routing/appformer/uberfire-commons/src/main/java/org/uberfire/commons/cluster/events/ClusterEventObserver.java:[19,24] cannot find symbol
  [ERROR]   symbol:   class PreDestroy
  [ERROR]   location: package javax.annotation
  [ERROR] /home/runner/work/optaweb-vehicle-routing/optaweb-vehicle-routing/appformer/uberfire-commons/src/main/java/org/uberfire/commons/cluster/events/ClusterEventObserver.java:[66,6] cannot find symbol
  [ERROR]   symbol:   class PreDestroy
  [ERROR]   location: class org.uberfire.commons.cluster.events.ClusterEventObserver
```
@Ginxo are you aware of this problem?

**Comment by Ginxo** [comment]
@yurloc yes we are, every java11 cross pull request build will fail from appformer.
Just `lienzo-core`, `lienzo-tests`, `droolsjbpm-build-bootstrap` and `kie-soup` java11 build is working for now
Thanks for checking!

**Comment by yurloc** [comment]
@Ginxo OK, thanks for explaining.

**Comment by yurloc** [comment]
@Ginxo FYI, we've recently introduced Maven dependencies caching in optaplanner: https://github.com/kiegroup/optaplanner/pull/932. We're still evaluating whether everything works as expected after introducing this but otherwise it significantly speeds up the build and reduces the number of Maven central requests (less requests => lower chance of timing out). You might be interested to check this out.

**Comment by Ginxo** [comment]
@mareknovotny we should investigate and consider https://github.com/kiegroup/optaplanner/pull/932 for the rest of the flows.
Adding subject to today's meeting.
Thanks @yurloc

**Comment by mareknovotny** [comment]
@yurloc until this GWT 2.9.0 is merged Appformer and followed up GWT based repos won't compile https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1442

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
