### PR TITLE
pull request flow updated to use github-action-build-chain@v2.1

### PR DESCRIPTION
**Pull request by Ginxo**
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]
lgtm

**Comment by Ginxo** [comment]
can you please guys review this
@caponetto @yurloc @rsynek ? Thanks

**Review by caponetto — APPROVED** [review]
LGTM

**Comment by rsynek** [comment]
LGTM

**Pull request merged**
