### PR TITLE
Upgrade frontend-maven-plugin for Apple Silicon support

### PR DESCRIPTION
**Pull request by teejae**
- Upgrade frontend-maven-plugin `1.10.0` -> `1.11.3`, which correctly installs npm on Apple Silicon.

### JIRA

Same issue as:
https://github.com/kiegroup/optaweb-employee-rostering/issues/608

### Tasks
- [x] Replicate the change in https://github.com/kiegroup/optaweb-employee-rostering.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] LTS</b>

</details>

### CODE REVIEW

**Comment by triceo** [comment]
OK to test.

**Comment by yurloc** [comment]
Anyone who merges this, please make sure the same update is done for `optaweb-employee-rostering`.

@teejae Feel free to do that but it's not a requirement. We'll take care of that if you don't. Thanks for the contribution!

**Comment by teejae** [comment]
@yurloc, I believe there's an even newer version of the frontend-maven-plugin. Should we upgrade to the newest (1.12)? I haven't particularly tested it however.

https://mvnrepository.com/artifact/com.github.eirslett/frontend-maven-plugin

**Comment by teejae** [comment]
> Anyone who merges this, please make sure the same update is done for `optaweb-employee-rostering`.
> 
> @teejae Feel free to do that but it's not a requirement. We'll take care of that if you don't. Thanks for the contribution!

Done

**Comment by teejae** [comment]
@Christopher-Chianelli @yurloc will you be handling the merge of this PR separately? should i revert the package-lock.json?

**Comment by teejae** [comment]
per suggestion from @Christopher-Chianelli, i've reverted the `package-lock.json`.

@yurloc up to you to merge?

**Pull request merged**
