### PR TITLE
BXMSPROD-494 allow GA build on windows machine

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-494

related to

https://github.com/kiegroup/lienzo-core/pull/133
https://github.com/kiegroup/lienzo-tests/pull/108
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1471
https://github.com/kiegroup/kie-soup/pull/158
https://github.com/kiegroup/appformer/pull/1054
https://github.com/kiegroup/droolsjbpm-knowledge/pull/465
https://github.com/kiegroup/drools/pull/3116
https://github.com/kiegroup/optaplanner/pull/940
https://github.com/kiegroup/jbpm/pull/1758
https://github.com/kiegroup/kie-jpmml-integration/pull/43
https://github.com/kiegroup/droolsjbpm-integration/pull/2243
https://github.com/kiegroup/openshift-drools-hacep/pull/100
https://github.com/kiegroup/droolsjbpm-tools/pull/118
https://github.com/kiegroup/kie-uberfire-extensions/pull/106
https://github.com/kiegroup/kie-wb-playground/pull/97
https://github.com/kiegroup/kie-wb-common/pull/3423
https://github.com/kiegroup/drools-wb/pull/1423
https://github.com/kiegroup/optaplanner-wb/pull/381
https://github.com/kiegroup/jbpm-designer/pull/891
https://github.com/kiegroup/jbpm-wb/pull/1461
https://github.com/kiegroup/jbpm-work-items/pull/153
https://github.com/kiegroup/kie-docs/pull/2849
https://github.com/kiegroup/optaweb-employee-rostering/pull/498
https://github.com/kiegroup/optaweb-vehicle-routing/pull/367
https://github.com/kiegroup/kie-wb-distributions/pull/1062

### CODE REVIEW

**Comment by yurloc** [comment]
@Ginxo `free disk space` step fails. `sudo` doesn't work on Windows.

**Comment by mareknovotny** [comment]
we need to rebase this @Ginxo

**Comment by Ginxo** [comment]
I'm afraid we will have disk space problem on windows running... let's see result

**Comment by Ginxo** [comment]
windows error: `unable to create file optaplanner-persistence/optaplanner-persistence-xstream/src/test/java/org/optaplanner/persistence/xstream/api/score/buildin/simplebigdecimal/SimpleBigDecimalScoreXStreamConverterTest.java: Filename too long`
on ubuntu: `Cypress failed to verify that your server is running.`  I would try to relaunch.

**Comment by Ginxo** [comment]
after adding 
```
- name: Support longpaths
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true
```
a new error appears on windows build
```
2021-03-11T11:08:52.9082205Z [INFO] --- exec-maven-plugin:1.6.0:exec (run-cypress-tests) @ optaweb-vehicle-routing-standalone ---
2021-03-11T11:08:57.9229931Z Unable to find image 'cypress/included:4.12.1' locally
2021-03-11T11:08:58.6982644Z 4.12.1: Pulling from cypress/included
2021-03-11T11:08:58.7776580Z docker: image operating system "linux" cannot be used on this platform.
2021-03-11T11:08:58.7777827Z See 'docker run --help'.
2021-03-11T11:08:58.8696420Z [ERROR] Command execution failed.
2021-03-11T11:08:58.8716132Z org.apache.commons.exec.ExecuteException: Process exited with an error: 125 (Exit value: 125)
```

**Comment by mareknovotny** [comment]
ok, so that is out of luck as docker can be installed in special installation only it seems?

**Comment by Ginxo** [comment]
> ok, so that is out of luck as docker can be installed in special installation only it seems?

Maybe @yurloc can clarify something here...

**Comment by yurloc** [comment]
We can ignore the Cypress error (`Cypress failed to verify that your server is running.`). The Cypress test fails because the backend has been broken by a Spring Boot upgrade (https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1590).

I don't know whether the Cypress docker image is supposed to run on Windows. I won't be able to look into that this week. But I can imagine skipping the Cypress tests on Windows. Wdyt @dupliaka?

**Comment by dupliaka** [comment]
> We can ignore the Cypress error (`Cypress failed to verify that your server is running.`). The Cypress test fails because the backend has been broken by a Spring Boot upgrade ([kiegroup/droolsjbpm-build-bootstrap#1590](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1590)).
> 
> I don't know whether the Cypress docker image is supposed to run on Windows. I won't be able to look into that this week. But I can imagine skipping the Cypress tests on Windows. Wdyt @dupliaka?

Yes, till now cypress tests on windows was running on podman

**Comment by Ginxo** [comment]
@mareknovotny please review

**Comment by yurloc** [comment]
Jenkins retest this.

**Comment by Ginxo** [comment]
@mareknovotny can you please merge?

**Comment by mareknovotny** [comment]
@Ginxo hmm, I am not sure i get it from @dupliaka if the podman should work on windows or not.

The latest run https://github.com/kiegroup/optaweb-vehicle-routing/pull/367/checks?check_run_id=2173813110 still fails on cypress init from container.

**Comment by dupliaka** [comment]
> @Ginxo hmm, I am not sure i get it from @dupliaka if the podman should work on windows or not.
> 
> The latest run https://github.com/kiegroup/optaweb-vehicle-routing/pull/367/checks?check_run_id=2173813110 still fails on cypress init from container.

https://rhba-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/BxMS/job/RHPAM-master-nightly/job/certification/job/optaweb/job/blessed-optaweb-employee-rostering-jvmos-matrix/jdk=openjdk11,label_exp=w2k16/


Sorry I meant that this tests are working on Jenkins with podman on windows, however from the log it seems like it have been running on docker instead.

**Comment by Ginxo** [comment]
thanks @dupliaka for the explanation.
This is the latest updated I've found from github people
https://github.com/actions/virtual-environments/issues/2216#issuecomment-740412472 & https://github.community/t/github-actions-windows-runtime-linux-container-mode-docker/135874/4

So I guess we can't support windows execution for now

**Review by mareknovotny — APPROVED** [review]
now it is green, even there is some leftover job Maven(11) i didn't find it as existing GA or Jenkins CI, so ignoring that  and mark this as Approved and Green

**Comment by dupliaka** [comment]
@Ginxo That is because the cypress test was not launched

**Pull request merged**
