### PR TITLE
Remove AssertJ dependency version

### PR DESCRIPTION
**Pull request by cuijulian**
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1100

### CODE REVIEW

**Comment by yurloc** [comment]
Jenkins retest this.

**Comment by cuijulian** [comment]
Jenkins retest this

**Comment by yurloc** [comment]
What's the point of managing test scope dependencies?

**Comment by cuijulian** [comment]
I was under the impression that having a standard dependency version throughout `kie-parent` projects was ideal. Does this not apply to test scope dependencies?

**Pull request merged**
