### PR TITLE
BXMSPROD-1973 Update GHA setup-java to v3

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/BXMSPROD-1973

- https://github.com/kiegroup/kogito-pipelines/pull/868
- https://github.com/kiegroup/drools-website/pull/241
- https://github.com/kiegroup/kogito-runtimes/pull/2811
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/847
- https://github.com/kiegroup/optaplanner-website/pull/570

### CODE REVIEW

**Review by Ginxo — APPROVED** [review]
LGTM

**Review by mbiarnes — APPROVED** [review]

**Comment by lampajr** [comment]
PRs checks are failing because I think the working directory is different now [1]: it should be `kiegroup_optaweb-vehicle-routing/optaweb-vehicle-routing`

[1] https://github.com/kiegroup/optaweb-vehicle-routing/blob/main/.github/workflows/pull_request.yml

**Comment by lampajr** [comment]
If my guess is correct https://github.com/kiegroup/optaweb-vehicle-routing/pull/848 should fix it.

**Review by lampajr — APPROVED** [review]

**Comment by radtriste** [comment]
known issue on Productized Build-Chain

**Pull request merged**
