### PR TITLE
Upgrade vulnerable node-forge to 0.10.0

### PR DESCRIPTION
**Pull request by yurloc**
### Referenced pull requests

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by Christopher-Chianelli — CHANGES_REQUESTED** [review]
I don't see any changes to `package.json`, only `package-lock.json`. Is this an update of one of our dependencies' dependencies (i.e. not one of our dependencies, but one we inherited)? If not (i.e. it is one of our dependencies), I prefer `package.json` to be updated to reflect the version change (npm developers don't always respect minor = no breaking changes, and it be easier to look up the issue if we had the actual version being used in package.json). If not (transitive dependency), this is fine (although the dependency that introduce it wasn't updated).

**Comment by Christopher-Chianelli** [comment]
SonarCloud Code Analysis went to the OptaPlanner PR (https://github.com/kiegroup/optaplanner/pull/393): https://sonarcloud.io/dashboard?id=org.optaplanner%3Aoptaplanner&pullRequest=393

**Comment by yurloc** [comment]
@Christopher-Chianelli looks good?

**Comment by Christopher-Chianelli** [comment]
@yurloc see my comment from my review. If it an update to a dependency dependency, it good, if it an update to a direct dependency, I would prefer it to be reflected also in package.json (so we can easily look up any issues with the package)

**Comment by yurloc** [comment]
@Christopher-Chianelli good question. The change in `package-lock.json` is a result of running `npm audit fix`, which was a recommendation I got after running `npm audit`. I think it makes sense because `node-forge` is not my direct dependency so I shouldn't enforce its version in `package.json` but I can still fine-tune the dependency tree by changing `package-lock.json`.

**Review by Christopher-Chianelli — APPROVED** [review]

**Pull request merged**
