### PR TITLE
PLANNER-2595 Disable native CI

### PR DESCRIPTION
**Pull request by triceo**
Signed-off-by: Lukáš Petrovický <lpetrovi@redhat.com>

### Referenced pull requests

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] native</b>
</details>

### CODE REVIEW

**Review by yurloc — APPROVED** [review]
LGTM.

**Review by Christopher-Chianelli — APPROVED** [review]

**Comment by yurloc** [comment]
Jenkins run tests

**Comment by mbiarnes** [comment]
Jenkins run optaweb-vehicle-routing tests

**Comment by mbiarnes** [comment]
Jenkins run optaweb-vehicle-routing tests

**Comment by mbiarnes** [comment]
Jenkins run optaweb-vehicle-routing tests

**Comment by yurloc** [comment]
The `(build) optaweb-vehicle-routing` check doesn't start because the changes in this PR are in the "excluded regions" only.

The check uses default parameters from `KogitoJobTemplate`: https://github.com/kiegroup/optaweb-vehicle-routing/blob/3278d5c56b52408cb635ef5a6af19d7b2acbecd3/.ci/jenkins/dsl/jobs.groovy#L3-L5

which are defined here: https://github.com/kiegroup/kogito-pipelines/blob/58d117dc2801daa7cb64638fda34966f855575ef/dsl/seed/src/main/groovy/org/kie/jenkins/jobdsl/templates/KogitoJobTemplate.groovy#L475-L501

**Pull request merged**
