### PR TITLE
[7.x] BXMSPROD-1558 @kie/lock-treatment-tool

### PR DESCRIPTION
**Pull request by Ginxo**
### JIRA

https://issues.redhat.com/browse/BXMSPROD-1558

### Referenced pull requests

* https://github.com/kiegroup/optaweb-vehicle-routing/pull/619
* https://github.com/kiegroup/optaweb-employee-rostering/pull/734

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] LTS</b>

</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins retest this

**Review by mareknovotny — APPROVED** [review]

**Review by yurloc — CHANGES_REQUESTED** [review]
`package-lock.json` modifications.

**Review by yurloc — CHANGES_REQUESTED** [review]
It's getting better but there are still `package-lock.json` modifications after running `mvn clean install`.

**Comment by Ginxo** [comment]
> It's getting better but there are still `package-lock.json` modifications after running `mvn clean install`.

package-lock.json file updated

**Review by yurloc — CHANGES_REQUESTED** [review]
Current diff (shortened to show a few different types of changes):

```diff
:100644 100644 18b266ab 00000000 M	optaweb-vehicle-routing-frontend/package-lock.json

diff --git a/optaweb-vehicle-routing-frontend/package-lock.json b/optaweb-vehicle-routing-frontend/package-lock.json
index 18b266ab..252ba697 100644
--- a/optaweb-vehicle-routing-frontend/package-lock.json
+++ b/optaweb-vehicle-routing-frontend/package-lock.json
@@ -2413,28 +2413,19 @@
         "resolve": "^1.3.2",
         "semver": "^5.4.1",
         "source-map": "^0.5.0"
-      },
-      "engines": {
-        "node": ">=6.9.0"
       }
     },
     "node_modules/@kie/lock-treatment-tool/node_modules/@babel/core/node_modules/semver": {
       "version": "5.7.1",
       "resolved": "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz",
       "integrity": "sha512-sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==",
-      "extraneous": true,
-      "bin": {
-        "semver": "bin/semver"
-      }
+      "extraneous": true
     },
     "node_modules/@kie/lock-treatment-tool/node_modules/@babel/core/node_modules/source-map": {
       "version": "0.5.7",
       "resolved": "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz",
       "integrity": "sha1-igOdLRAh0i0eoUyA2OpGi6LvP8w=",
-      "extraneous": true,
-      "engines": {
-        "node": ">=0.10.0"
-      }
+      "extraneous": true
     },
     "node_modules/@kie/lock-treatment-tool/node_modules/@babel/generator": {
       "version": "7.7.2",
@@ -9007,9 +7725,6 @@
       "extraneous": true,
       "dependencies": {
         "mkdirp": "^0.5.1"
-      },
-      "engines": {
-        "node": ">=4"
       }
     },
     "node_modules/@kie/lock-treatment-tool/node_modules/write-file-atomic": {
@@ -19972,12 +18687,6 @@
         "node": ">= 0.8.0"
       }
     },
-    "node_modules/line-reader": {
-      "version": "0.3.1",
-      "resolved": "https://registry.npmjs.org/line-reader/-/line-reader-0.3.1.tgz",
-      "integrity": "sha1-IVjAaxqz7SgjhTW5eq66nxeUm7s=",
-      "dev": true
-    },
     "node_modules/lines-and-columns": {
       "version": "1.1.6",
       "resolved": "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.1.6.tgz",
@@ -46256,11 +44965,6 @@
         "type-check": "~0.3.2"
       }
     },
-    "line-reader": {
-      "version": "https://registry.npmjs.org/line-reader/-/line-reader-0.3.1.tgz",
-      "integrity": "sha1-IVjAaxqz7SgjhTW5eq66nxeUm7s=",
-      "dev": true
-    },
     "lines-and-columns": {
       "version": "1.1.6",
       "resolved": "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.1.6.tgz",

```

I suggest that we merge #621 first so that GHA check this automatically. I've already spent quite some time doing this on my local machine.

Anyway, I'm wondering why this issue keeps recurring on this PR. For the record, I get the above diff after running `mvn clean install -U` in the root of the repository with
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/jlocker/apache-maven-3.6.3
Java version: 11.0.13, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc33.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.14.18-100.fc33.x86_64", arch: "amd64", family: "unix"
```

@Ginxo I can see two possible explanations of why your `package-lock.json` is different from mine:

A) You're doing `npm i` and your Npm version is different than the one used by the Frontend plugin. Or similar reason. In that case, please do a clean Maven build before committing and pushing. I expect that this should be easy to fix if that's the case.

B) If you are doing a Maven build, this becomes a much more interesting problem and we need to investigate this further. If we're doing the same steps and we're getting different results, the problem might be on my side even. If this is the case, please do approve #621 because I believe the CI environment is a good reference. If the Maven build ends up with a clean working tree, then the PR is good and there's a problem on my side.

**Comment by Ginxo** [comment]
`git diff HEAD` still failing after executing maven command and pushing the changes. What did I do?

- checkout 7.x
- create a new branch BXMSPROD-1558_7.x
- pom.xml and package.json modifications
- run `mvn clean install -U` command
- add and commit package.json package-lock.json and pom.xml files

any idea @yurloc ? :thinking: 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/emingora/development/software/apache-maven-3.6.3
Java version: 11.0.8, vendor: Oracle Corporation, runtime: /home/emingora/development/software/jdk-11.0.8_linux-x64_bin/jdk-11.0.8
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.14-100.fc32.x86_64", arch: "amd64", family: "unix"
```

npm 7.15.1 installed, node v12.22.5

**Comment by yurloc** [comment]
> npm 7.15.1 installed, node v12.22.5

I assume that what you have installed doesn't matter because the Frontend plugin uses Node and Npm versions are defined in the POM.

I've also tried this specific combination by running `mvn clean install -nsu -Dquickly -Dversion.npm=7.15.1 -Dversion.node=v12.22.5` on 7176c1fc35df03eb06b003eac3345e07fe095212 and I still get the same result as always - the same diff as above.

I have two ideas:
1. Try `rm -rf node_modules/` before building the project.
2. Make sure Npm 7.15.1 is really used during the build by observing this part of the output:
    ```
    [INFO] --- frontend-maven-plugin:1.8.0:install-node-and-npm (install node and npm) @ optaweb-vehicle-routing-frontend ---
    [INFO] Node v12.16.2 is already installed.
    [INFO] NPM 7.15.1 is already installed.
    ```

The `engines` and `bin` fields seem to have been added in Npm 7.x: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json. That makes me think they actually should be there as this PR is proposing, and not removed as we can see in GHA and on my machine.

**Comment by yurloc** [comment]
> That makes me think they actually should be there as this PR is proposing, and not removed as we can see in GHA and on my machine.

This is a red herring. Although the CI diff shows some `engines` fields being removed, I can still find 1225 occurrences in `package-lock.json`.

That leaves me with just one idea left: try removing all cached dependencies and tools that you can and make sure that you're really using the exact Npm and Node versions as declared in the POM (`kie-parent`).

**Comment by Ginxo** [comment]
@yurloc 

- node_modules removed
- npm cache clean

nothing changes... can you please @yurloc  push your package-lock.json either here and https://github.com/kiegroup/optaweb-employee-rostering/pull/734 in order to unlock productization nightly build and I will investigate the reason why this is happening ?

thanks a lot!

**Comment by yurloc** [comment]
> push your package-lock.json either here and [kiegroup/optaweb-employee-rostering#734](https://github.com/kiegroup/optaweb-employee-rostering/pull/734) in order to unlock productization nightly build

Yes, definitely. I came to the same conclusion.

**Review by yurloc — APPROVED** [review]

**Pull request merged**
