### PR TITLE
RHDM-1129: locktt execution added to productized profile, prepare-package phase

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.jboss.org/browse/RHDM-1129

depends on
- https://issues.jboss.org/browse/BXMSPROD-597 https://github.com/kiegroup/optaweb-vehicle-routing/pull/234
- and https://issues.jboss.org/browse/BXMSPROD-580 https://github.com/kiegroup/optaweb-vehicle-routing/pull/228

### CODE REVIEW

**Comment by mareknovotny** [comment]
all parent poms are merged and this is green, is it ok to merge this? @yurloc ?

**Comment by yurloc** [comment]
@rsynek Wdyt? Does this fix https://issues.jboss.org/browse/RHDM-1129?

**Comment by rsynek** [comment]
The tool removes URL from package-lock.json, but exact versions of dependencies stay. All tests still pass after the described transformation of the package-lock.json file.
=> LGTM

**Comment by Ginxo** [comment]
https://github.com/kiegroup/optaweb-employee-rostering/pull/351

**Pull request merged**
