### PR TITLE
Bump Quarkus 2.3.0.Final

### PR DESCRIPTION
**Pull request by radtriste**
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1634
- https://github.com/kiegroup/optaplanner/pull/1593
- https://github.com/kiegroup/kogito-apps/pull/1044
- https://github.com/kiegroup/kogito-examples/pull/909
- https://github.com/kiegroup/optaplanner-quickstarts/pull/190
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/570

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>specific pull request build</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] tests</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
* for a <b>Quarkus LTS check</b> please add comment: <b>Jenkins run LTS</b>
* for a <b>specific Quarkus LTS check</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] LTS</b>
* for a <b>Native check</b> please add comment: <b>Jenkins run native</b>
* for a <b>specific Native LTS check</b> please add comment: <b>Jenkins (re)run [optaweb-vehicle-routing] native</b>
</details>

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins retest this

**Review by yurloc — CHANGES_REQUESTED** [review]
I'm looking into the issue and I came to a conclusion that this type of workaround is not what I want. I don't want a default value for the credentials because I want the app to fail fast if the user doesn't provide them.

With the defaults, the build will silently (successfully) produce a binary with wrong credentials; the user will only find out when they try to deploy it.

What I was about to do was to move the Postgres config under a `%postgres` profile (Employee Rostering already does this). This way, the default build won't be disrupted but if the user wants to build for PostgreSQL, they will activate the profile and the build **will fail fast** if they do not provide any credentials.

**Comment by yurloc** [comment]
@radtriste I can open a PR with the fix described above in a minute. Shall we close this or do you want to take care of that?

**Comment by radtriste** [comment]
> I'm looking into the issue and I came to a conclusion that this type of workaround is not what I want. I don't want a default value for the credentials because I want the app to fail fast if the user doesn't provide them.
> 
> With the defaults, the build will silently (successfully) produce a binary with wrong credentials; the user will only find out when they try to deploy it.
> 
> What I was about to do was to move the Postgres config under a `%postgres` profile (Employee Rostering already does this). This way, the default build won't be disrupted but if the user wants to build for PostgreSQL, they will activate the profile and the build **will fail fast** if they do not provide any credentials.

I am good with that. Can you fix that directly on optaweb and once merged, close that one and restart the optaweb check on https://github.com/kiegroup/optaplanner/pull/1593 ?

**Comment by yurloc** [comment]
> > I'm looking into the issue and I came to a conclusion that this type of workaround is not what I want. I don't want a default value for the credentials because I want the app to fail fast if the user doesn't provide them.
> > With the defaults, the build will silently (successfully) produce a binary with wrong credentials; the user will only find out when they try to deploy it.
> > What I was about to do was to move the Postgres config under a `%postgres` profile (Employee Rostering already does this). This way, the default build won't be disrupted but if the user wants to build for PostgreSQL, they will activate the profile and the build **will fail fast** if they do not provide any credentials.
> 
> I am good with that. Can you fix that directly on optaweb and once merged, close that one and restart the optaweb check on [kiegroup/optaplanner#1593](https://github.com/kiegroup/optaplanner/pull/1593) ?

Yup, sounds good.

**Pull request closed without merging**
