### PR TITLE
BXMSPROD-560 lock-treatment-tool execution moved to defult profile

### PR DESCRIPTION
**Pull request by Ginxo**
BXMSPROD-560

### CODE REVIEW

**Comment by Ginxo** [comment]
@yurloc travis failed due to
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by Ginxo** [comment]
@yurloc anyway we should probably remove https://github.com/kiegroup/optaweb-vehicle-routing/blob/765f8728bc8fbd14f606fd21ec81dbd53955840c/.travis.yml#L20 since the locktt is executed WDYT?

**Comment by mareknovotny** [comment]
@Ginxo if you think to remove that line in .travis.yml please do to see the Travis CI green ;)

**Comment by Ginxo** [comment]
@mareknovotny green
@yurloc please review

**Comment by yurloc** [comment]
Merge conflict.

**Comment by mareknovotny** [comment]
@yurloc ? see above "This branch has no conflicts with the base branch"

**Comment by yurloc** [comment]
I'm sorry that conflict message was only valid for rebase. I'll squash this so no problem.

**Comment by yurloc** [comment]
@Ginxo Example of the `before_script` check in action: https://travis-ci.com/kiegroup/optaweb-vehicle-routing/builds/136503843.

**Comment by Ginxo** [comment]
@yurloc .travis changes reverted

**Comment by yurloc** [comment]
Jenkins retest this.

**Pull request merged**
