### PR TITLE
PLANNER-2199: Upgrade OptaPlanner to 8.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by yurloc**
### JIRA

https://issues.redhat.com/browse/PLANNER-2199

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by triceo — APPROVED** [review]
LGTM. If I were you, I'd reconsider upgrading the solver and benchmark configs to use the XSDs.

**Comment by rsynek** [comment]
@yurloc I would be very interested in hearing how the upgrade of  the config xml goes. So far we at least know the backward compatibility works.

**Comment by Christopher-Chianelli** [comment]
Given `optaweb-vehicle-routing` has a 7.x branch, shouldn't the project version (of `optaweb-vehicle-routing` and its modules) also be updated to 8.0.0-SNAPSHOT on the master branch?

**Comment by triceo** [comment]
@Christopher-Chianelli @yurloc It probably should. `7.x` is definitely wrong, but we could reconsider if perhaps we want to version Optawebs differently, as they're apps - `1.0.0-SNAPSHOT` perhaps.

But that's just change for change's sake. I suggest we keep in line with OptaPlanner, and that's that.

**Comment by yurloc** [comment]
Superseded by #384.

**Pull request closed without merging**
