### PR TITLE
Change configuration to new OCP 4.5.1 standart

### PR DESCRIPTION
**Pull request by dupliaka**
Made runOnOpenShift.sh to store configurations
into Deployments instead of DeploymentsConfig

### CODE REVIEW

**Comment by rsynek** [comment]
@dupliaka would you please explain what's the motivation for changing DeploymentConfig to Deployment? According to OCP 4.5.0 documentation, both should be supported (although Deployment is preferred unless DC is specifically needed):
https://docs.openshift.com/container-platform/4.5/applications/deployments/what-deployments-are.html#deployments-comparing-deploymentconfigs_what-deployments-are

**Comment by dupliaka** [comment]
> @dupliaka would you please explain what's the motivation for changing DeploymentConfig to Deployment? According to OCP 4.5.0 documentation, both should be supported (although Deployment is preferred unless DC is specifically needed):
> https://docs.openshift.com/container-platform/4.5/applications/deployments/what-deployments-are.html#deployments-comparing-deploymentconfigs_what-deployments-are

Unfortunately, I am not so good in Openshift yet, so I noticed that because I was tracking this issue, and @jakubschwan advised me to check that :+1: "DeploymentConfig (Deployment is from Kubernetise definition, DeploymentConfig is old format from OCP that was used and bring before Deployments)
so Deployment is more generic in Kubernetes word, DeploymnetConfig is OCP specification"
so I did +  I changed local OCP version to the latest one, reproduced the bug and by changing DeploymentConfig to Deployment just helped me.

**Comment by jakubschwan** [comment]
Actually it looks like that in OCP 4.5+ command `oc new app` generated Deployment instead of DeploymentConfig

See OCP release notes https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html

Copied from release notes:

Developer experience
oc new-app now produces Deployment resources

The oc new-app command now produces Deployment resources instead of DeploymentConfig resources by default. If you prefer to create DeploymentConfig resources, you can pass the --as-deployment-config flag when invoking oc new-app. For more information, see Understanding Deployments and DeploymentConfigs.

**Comment by dupliaka** [comment]
@rsynek @jakubschwan could somebody point me to Travis specialist? I can see it is queued and at the same time each build has been already complited

**Comment by yurloc** [comment]
@dupliaka Let's ignore the queued travis build. I think the check became stale. Maybe it's because you renamed the PR before the build finished. Anyway, the other check has passed, so it's OK.

**Comment by yurloc** [comment]
Jenkins retest this.

**Comment by yurloc** [comment]
@dupliaka Looks good, thanks for the contribution! What kind of OpenShift have you tested this against? CRC, OpenShift Online, an internal instance?

**Comment by dupliaka** [comment]
> @dupliaka Looks good, thanks for the contribution! What kind of OpenShift have you tested this against? CRC, OpenShift Online, an internal instance?

CodeReady Containers version: 1.13.0+8070bae
OpenShift version: 4.5.1 (embedded in binary)   

Client Version: 4.5.1
Server Version: 4.5.2
Kubernetes Version: v1.18.3+b74c5ed

**Comment by dupliaka** [comment]
Jenkins retest this.

**Comment by dupliaka** [comment]
@kiegroup/gatekeepers Could you merge this pr since it is approved but Travis still shows queued while each job has been successfully finished?

**Pull request merged**
