### PR TITLE
BAQE-1008 Report frontend tests results in junit format

### PR DESCRIPTION
**Pull request by rsynek**
To unify test result format due to internal tooling.

### CODE REVIEW

**Comment by yurloc** [comment]
I'm getting an error when running `npm test` locally:
```
Determining test suites to run...

  ● Test suite failed to run

    Configuration error:
    
    Could not locate module react-native mapped as:
    react-native-web.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^react-native$/": "react-native-web"
      },
      "resolver": null
    }

      at createNoMappedModuleFoundError (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:472:17)
          at Array.reduce (<anonymous>)
      at SearchSource.findRelatedTests (node_modules/@jest/core/build/SearchSource.js:280:30)
      at SearchSource.findTestRelatedToChangedFiles (node_modules/@jest/core/build/SearchSource.js:363:14)
```

Have you seen this?

**Comment by yurloc** [comment]
Jenkins retest this.

**Comment by rsynek** [comment]
@yurloc the build is still broken. Is somebody looking into that or should I contact an owner of the repository?

**Comment by yurloc** [comment]
@rsynek I'm not worried about Jenkins that much. Marek is aware of the issue. I hope somebody is working on it.

You have accidentally committed redhat.com URLs to package-lock.json. I'd like to first merge #198  and see Travis build fail before you fix it so that we have a visible proof that the check works and this will be caught in the future.

Please approve #198.

**Comment by rsynek** [comment]
@yurloc I see, I quickly glanced over the package-lock.json, but didn't realize the URLs will change only for the updated dependencies.

**Pull request merged**
