### PR TITLE
PLANNER-2467 Jenkinsfiles moved to .ci/jenkins

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/PLANNER-2467

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1025
* https://github.com/jboss-integration/rhba/pull/42
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1688
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/526
* https://github.com/kiegroup/optaweb-employee-rostering/pull/651
* https://github.com/kiegroup/optaplanner/pull/1414

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
@rsynek @yurloc @ge0ffrey I'm not sure about how this movement affects to Jenkins. Can you please provide some information? thanks.

**Comment by yurloc** [comment]
@Ginxo I think that jobs need to be updated to specify script path as `.ci/Jenkinsfile`. See https://www.jenkins.io/doc/book/pipeline/getting-started/#defining-a-pipeline-in-scm.

Good to merge when the build is green.

**Comment by Ginxo** [comment]
> @Ginxo I think that jobs need to be updated to specify script path as `.ci/Jenkinsfile`. See https://www.jenkins.io/doc/book/pipeline/getting-started/#defining-a-pipeline-in-scm.
> 
> Good to merge when the build is green.

@yurloc the optaplanner job creation has been already updated by https://github.com/kiegroup/optaplanner/pull/2. The CI error is not due to this change itself but to build-chain mapping error. I've already open a ticket for this https://issues.redhat.com/browse/BXMSPROD-1413 (not sure it's about project-dependencies definition error or build-chain tool itself)
do you agree to merge?

**Review by ge0ffrey — APPROVED** [review]

**Comment by Ginxo** [comment]
@yurloc can you please check PRs from https://issues.redhat.com/browse/BXMSPROD-1340?. I will rebase these set of PLANNER-2467 PRs after merging the ones from BXMSPROD-1340.
Thanks!

**Pull request merged**
