### PR TITLE
[8.13.x] RHPAM-4817: Update backend Dockerfiles and configuration to Quarkus 2.13.8

### PR DESCRIPTION
**Pull request by yurloc**
- Update Dockerfiles.
- Explicitly allow all origins to fix a CORS issue caused by https://github.com/quarkusio/quarkus/pull/33439.

### JIRA
- https://issues.redhat.com/browse/RHPAM-4817

### CODE REVIEW

**Comment by kie-ci1** [comment]
**(tests) - optaweb-vehicle-routing job** `#13` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/optaweb-vehicle-routing.tests.optaweb-vehicle-routing/13/display/redirect

**Test results:**
- PASSED: 248
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-10-17T13:10:29.433Z] [INFO] Will not upload any artifacts in CLI environment<br/>[2023-10-17T13:10:29.433Z]  <br/>[Pipeline] }<br/>[Pipeline] // withCredentials<br/>[Pipeline] }<br/>[2023-10-17T13:10:29.494Z] Deleting 1 temporary files<br/>[Pipeline] // configFileProvider<br/>[Pipeline] }<br/>[Pipeline] // script<br/>Post stage<br/>[Pipeline] junit<br/>[2023-10-17T13:10:29.576Z] Recording test results<br/>[2023-10-17T13:10:31.909Z] [Checks API] No suitable checks publisher found.<br/>[Pipeline] archiveArtifacts<br/>[2023-10-17T13:10:31.923Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-10-17T13:10:35.241Z] + wget --no-check-certificate -qO - 'https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/1.13.x/job/pullrequest/job/optaweb-vehicle-routing.tests.optaweb-vehicle-routing/13/api/json?depth=0'<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

**Comment by dupliaka** [comment]
LGTM

**Review by dupliaka — APPROVED** [review]

**Comment by mareknovotny** [comment]
thnx for the fix @yurloc 

fyi @rgdoliveira,  we probably need this for the build too, right?

**Comment by rgdoliveira** [comment]
@mareknovotny TBH I don't know, I mean, I dont see any direct reference to Quarkus version in this PR, so maybe this can be merged only for RHPAM 7.13.5 and skipped from the respin? (cc @yurloc ).

Also we dont need this to be backported to 8.13.x-blue branch, as optaplanner projects were dropped from there.

**Comment by yurloc** [comment]
@rgdoliveira The PR title may have been a bit confusing, sorry for that. I've updated it.

What this PR actually does is that it updates backend Dockerfiles and configuration (`application.properties`) to fix two bugs that were introduced by several Quarkus updates made this year and which only manifested now during QE tests.

Quarkus upgrades:
- 2.13.4: https://github.com/kiegroup/optaplanner/commit/b5bf6b65c777dbef00ba5ac75e9554218c26c583
- 2.13.7: https://github.com/kiegroup/optaplanner/commit/83f467932918236d6ffaec71f0ad7cefc5ced1cd
- 2.13.8: https://github.com/kiegroup/optaplanner/commit/3bb2065178af5e8cd90cdb201f24575e3182ff93

This PR is needed to make the QE CI pipeline green. @dupliaka please confirm.

**Review by pibizza — APPROVED** [review]
Looks Good to me

**Pull request merged**
