### PR TITLE
fix master pull request flow

### PR DESCRIPTION
**Pull request by Ginxo**
### Referenced pull requests

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by rsynek** [comment]
@Ginxo There is one important thing to note: repositories like kie-soup, appformer, etc., are irrelevant for the master branch of any optaplanner-related repository.

Shall we meet to discuss what this PR check should look like for optaplanner and optawebs?

**Comment by Ginxo** [comment]
> @Ginxo There is one important thing to note: repositories like kie-soup, appformer, etc., are irrelevant for the master branch of any optaplanner-related repository.
> 
> Shall we meet to discuss what this PR check should look like for optaplanner and optawebs?

@ge0ffrey @mareknovotny Wdyt about this? ^
do we remove build chain for master branch? is it fine to have it there?

**Comment by rsynek** [comment]
Don't get me wrong, the Build Chain might be very helpful here. Maybe for checking optaplanner with kogito, but also for optaplanner-related repositories themselves: optawebs depend on a snapshot of optaplanner, so we might be interested in checking them on optaplanner's PRs. Optaplanner-quickstarts are another example.

I like the potential benefits of the Build Chain, we just need to configure it correctly.

**Comment by yurloc** [comment]
Jeknins build failed due to `/usr/bin/docker-current: toomanyrequests: You have reached your pull rate limit.` which is expected these days. Otherwise the build looks healthy.

**Review by yurloc — APPROVED** [review]

**Pull request merged**
